### ISSUE TITLE
Application size increased 2.1x after upgrading from v1.3.2 to v2.2.0

### ISSUE THREAD

**Issue by deepfriedbrain** [GoogleCloudPlatform/app-maven-plugin#419] opened 2020-06-02 11:00 UTC
I upgraded the plugin version from `1.3.2` to `2.2.0`. My application is using App Engine Java SDK v1.9.79. Before upgrading the plugin, the app size on the app engine console was 14.9MB. After upgrading and deploying with the new plugin, it increased to 31.6MB. This is a 2.1 times increase.

Also, earlier I used to deploy it with the command `mvn appengine:deploy`. Now I need to run `mvn package appengine:deploy`. I don't quite understand why.

Can someone explain why the application size has increased considerably? Am I missing some configuration to bring it back to what it was?

**Comment by loosebazooka** [comment] 2020-06-19 18:19
application size should not have changed. `mvn package` is required because we no longer rebuild on every instance, only when the user initiates it.

**Comment by deepfriedbrain** [comment] 2020-06-21 03:51
The actual packaged war did not change in size, but after deployment to app engine, I see a huge difference in size on the Google Cloud -> App Engine -> Versions page. I reverted back 1.3.2 and size shrunk back to the original.

**Comment by deepfriedbrain** [comment] 2020-07-12 14:40
@loosebazooka I spent more time to test this today and the behavior (size increase) is consistently reproducible. I used GAE Java SDK 1.9.76 and gcloud version 253.0.0 for my tests.

1. My app with no code change when deployed using version `1.3.2` has a size of 15.1 MB (when viewed from the GAE Versions page). 
2. But when I switch to any of the `2.x` versions the application size becomes 31.3MB. I tried with `2.0.0-rc2`, `2.0.0`, `2.2.0`, and `2.3.0` and all resulted in the exact same size of 31.3MB.

My WAR file size on the local is 27MB in all the cases.

In all the cases, I used the following command to deploy:

`mvn clean package appengine:deploy`

Can you please help me figure out the reason for the increase in application size after deployment?

**Comment by loosebazooka** [comment] 2020-07-13 14:19
That's very strange. 
Can you check the size of the `appengine-staging` directory after running `mvn clean package appengine:stage`?

I see that you've mentioned that you're using `253.0.0` cloud sdk for both. In version maven plugin 2.0+, we have a managed cloud sdk that will auto install the latest SDK if not configured in the build file. Do you have that configured?

**Comment by deepfriedbrain** [comment] 2020-07-13 15:39
@loosebazooka Running the `appengine:stage` was a great idea. I managed to figure out that the bloated package with `2.3.0` was including `appengine-api-1.0-sdk-1.9.76.jar` whereas the one with `1.3.2` was not. This jar file is 16.9MB and was causing the application size to increase.

In my `pom.xml`, I do have this dependency: 

```
<dependency>
    <groupId>com.google.appengine</groupId>
    <artifactId>appengine-api-1.0-sdk</artifactId>
    <version>1.9.76</version>
</dependency>
```

Should I be removing it? If so, would there be a way to specify a particular version of the appengine SDK going forward?

**Comment by loosebazooka** [comment] 2020-07-13 15:42
It might have something to do with how the processing now occurs for appengine.
@ludoch @eamonnmcmanus do you have some information here?

**Comment by loosebazooka** [comment] 2020-07-13 15:43
I believe you need to keep that dependency in there.

**Comment by eamonnmcmanus** [comment] 2020-07-13 15:57
It used to be the case that we stripped `appengine-api.jar` from deployments, and supplied an up-to-date version at runtime instead. That made sense at a time when the API could evolve rapidly, but that's no longer happening. Meanwhile the substitution could also lead to surprising behaviour. So now we include your own SDK's version of `appengine-api.jar` in the deployment and that's what we use at runtime. That means that your deployment is bigger, but the actual runtime size of your app is still about the same, because you're just replacing one version of `appengine-api.jar` with another.

**Comment by chanseokoh** [comment] 2020-07-13 16:15
@deepfriedbrain saw your thumbs-up. I'll close this as "working as intended."

**Closed by chanseokoh** 2020-07-13 16:15 UTC

**Comment by deepfriedbrain** [comment] 2020-07-13 16:17
Thank you. I think it would be good to document this behavior though. I went through several channels before I came here looking for an answer.

**Comment by chanseokoh** [comment] 2020-07-13 16:48
This doesn't only apply to `appengine-maven-plugin` but to all other tools.

There's a bit of history to this. Previously, App Engine was providing `appengine-api-1.0.jar` at runtime (whose behavior the App Engine team said is a ["bug"](https://issuetracker.google.com/76144204#comment36)), and at that time, client tools (such as `appengine-maven-plugin`) were designed and running based on this assumption. In early 2018, the App Engine team fixed the "bug" and stopped providing the JAR at runtime. As one can imagine, this broke a lot of users, so they [reverted the change](https://issuetracker.google.com/76144204#comment36) soon. As explained in the comment, they suggested that client tools should now ensure that the JAR is included (if used). So the proper solution now is that each application should [include their `appengine-api.jar`](https://issuetracker.google.com/76144204#comment46). As they said, they do need to fix this "bug" and may again attempt to roll out the fix in the future, so it's important to keep the JAR in your runtime classpath. Or maybe the fix is already rolled out, based on what @eamonnmcmanus said above. I don't know the exact behavior either.

@ludoch @eamonnmcmanus that said, has this change in the `appengine-api-*.jar` assumption been documented somewhere? Release notes?
