### ISSUE TITLE
Unable to deploy to AppEngine following upgrade to Cloud SDK 201.0.0

### ISSUE THREAD

**Issue by AdamSantosCA** [GoogleCloudPlatform/app-maven-plugin#311] opened 2018-06-08 20:42 UTC
We just upgraded Cloud SDK on our Jenkins server from 184.0.0 to 201.0.0 and are now getting the following failures when deploying to AppEngine. It looks like the plugin thinks we are using a version of the SDK prior to 171.0.0.

mvn -B -V -Dmaven.javadoc.skip=true -Pdev1 appengine:deploy -DskipTests

12:00:57 [INFO] --- appengine-maven-plugin:1.3.2:deploy (default-cli) @ mobile-service ---
12:00:57 [INFO] Staging the application to: /media/jenkins2-storage/jenkins/workspace/_feature_ORG-3776-NativeIOS-R37GJLHYGMLKGAHMFBFREWZJNGHTVYD7SMTOL2EHZLLAPW36ZDDA/target/appengine-staging
12:00:57 [INFO] Detected App Engine standard environment application.
12:00:57 Jun 08, 2018 12:00:57 PM com.google.cloud.tools.appengine.cloudsdk.CloudSdk logCommand
12:00:57 INFO: submitting command: /usr/lib/jvm/java-8-oracle/jre/bin/java -cp /usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/appengine-tools-api.jar com.google.appengine.tools.admin.AppCfg --disable_update_check stage /media/jenkins2-storage/jenkins/workspace/_feature_ORG-3776-NativeIOS-R37GJLHYGMLKGAHMFBFREWZJNGHTVYD7SMTOL2EHZLLAPW36ZDDA/target/mobile-service-1.4.0-SNAPSHOT /media/jenkins2-storage/jenkins/workspace/_feature_ORG-3776-NativeIOS-R37GJLHYGMLKGAHMFBFREWZJNGHTVYD7SMTOL2EHZLLAPW36ZDDA/target/appengine-staging
12:00:58 [INFO] GCLOUD: Reading application configuration data...
12:00:58 [INFO] GCLOUD: 
12:00:58 [INFO] GCLOUD: 
12:00:58 [INFO] GCLOUD: Beginning interaction for module mobile...
12:00:59 [INFO] GCLOUD: 0% Scanning for jsp files.
12:00:59 [INFO] GCLOUD: 0% Generated git repository information file.
12:00:59 [INFO] GCLOUD: Success.
12:00:59 [INFO] GCLOUD: Temporary staging for module mobile directory left in /media/jenkins2-storage/jenkins/workspace/_feature_ORG-3776-NativeIOS-R37GJLHYGMLKGAHMFBFREWZJNGHTVYD7SMTOL2EHZLLAPW36ZDDA/target/appengine-staging
12:00:59 [INFO] ------------------------------------------------------------------------
12:00:59 [INFO] BUILD FAILURE
12:00:59 [INFO] ------------------------------------------------------------------------
12:00:59 [INFO] Total time: 9.953 s
12:00:59 [INFO] Finished at: 2018-06-08T12:00:59-07:00
12:00:59 [INFO] Final Memory: 30M/379M
12:00:59 [INFO] ------------------------------------------------------------------------
12:00:59 [ERROR] Failed to execute goal com.google.cloud.tools:appengine-maven-plugin:1.3.2:deploy (default-cli) on project mobile-service: Execution default-cli of goal com.google.cloud.tools:appengine-maven-plugin:1.3.2:deploy failed: Cloud SDK versions before 171.0.0 are not supported -> [Help 1]
12:00:59 [ERROR] 
12:00:59 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
12:00:59 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
12:00:59 [ERROR] 
12:00:59 [ERROR] For more information about the errors and possible solutions, please read the following articles:
12:00:59 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

+ gcloud --version
Google Cloud SDK 201.0.0
alpha 2018.05.11
app-engine-java 1.9.63
app-engine-python 1.9.67
beta 2018.05.11
bq 2.0.33
core 2018.05.11
gsutil 4.31

**Comment by chanseokoh** [comment] 2018-06-08 20:57
Just in case, do you see `/usr/lib/goolge-cloud-sdk/VERSION`? What is the content of the file? Are you using a package manager such as apt or yum?

**Comment by AdamSantosCA** [comment] 2018-06-08 21:38
We're using apt. 
Contents of /usr/lib/google-cloud-sdk:
`adam@jenkins2:/usr/lib/google-cloud-sdk$ ls -l`
`total 52`
`drwxr-xr-x 3 root root 4096 Jun  7 16:17 bin`
`-rw-r--r-- 1 root root 2083 Dec  1  2017 completion.zsh.inc`
`drwxr-xr-x 3 root root 4096 Dec  8 15:26 deb`
`-rwxr-xr-x 1 root root 1996 Dec  1  2017 install.bat`
`-rwxr-xr-x 1 root root 3701 Dec  1  2017 install.sh`
`drwxr-xr-x 6 root root 4096 Jun  7 16:17 lib`
`-rw-r--r-- 1 root root  980 Dec  1  2017 LICENSE`
`-rw-r--r-- 1 root root  324 Dec  1  2017 path.bash.inc`
`-rw-r--r-- 1 root root 1210 Dec  1  2017 path.fish.inc`
`-rw-r--r-- 1 root root   31 Dec  1  2017 path.zsh.inc`
`drwxr-xr-x 6 root root 4096 Nov 10  2017 platform`
`-rw-r--r-- 1 root root   39 May 11 08:39 properties`
`drwxr-xr-x 3 root root 4096 Dec  8 15:26 rpm`

**Comment by chanseokoh** [comment] 2018-06-08 21:58
Can you do `/usr/lib/google-cloud-sdk/bin/gcloud version` to rule out that you are picking up another SDK somewhere else?

If the above command does show version 201, I think it is a regression of https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/298. A workaround is to install an SDK directly. There is another hacky way of creating the `VERSION` file manually, but I do not recommend it because it can be messed up with future upgrade with the package manager.

**Comment by AdamSantosCA** [comment] 2018-06-08 22:06
Yes, we are using that version:

adam@jenkins2:/usr/lib/google-cloud-sdk/bin$ /usr/lib/google-cloud-sdk/bin/gcloud version
Google Cloud SDK 201.0.0
alpha 2018.05.11
app-engine-java 1.9.63
app-engine-python 1.9.67
beta 2018.05.11
bq 2.0.33
core 2018.05.11
gsutil 4.31

It does sound like a regression like you said. Perhaps your documentation can be updated to suggest a direct install of the SDK.

We'll reinstall and let you know if that resolves the issue. Thanks!

**Comment by loosebazooka** [comment] 2018-06-09 00:36
Thanks for all the feedback Adam, we're going to work with the Cloud SDK team to see how we can prevent this in the future.

**Comment by chanseokoh** [comment] 2018-06-13 19:18
@AdamSantosCA I think the 201 version at `/usr/lib/google-cloud-sdk/` has not been installed from our deb distribution source but rather likely from the Canonical deb. We noticed that SDKs packaged by Canonical don't include the `VERSION` file. When installing the SDK, you should follow the instructions below to pull an SDK packaged by Google. SDKs packaged by others are not really supported. I'd even say they are broken.

https://cloud.google.com/sdk/docs/quickstart-debian-ubuntu

**Comment by chanseokoh** [comment] 2018-06-14 20:14
@AdamSantosCA I'll close this, as you seem to be using an unsupported Cloud SDK packaged by a third party and moreover, you said you'll follow the workaround. If that is not the case, feel free to reopen.

**Closed by chanseokoh** 2018-06-14 20:14 UTC
