### ISSUE TITLE
GCS / Blobstore emulator not compatible

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/app-maven-plugin#142] opened 2017-02-27 20:17 UTC
https://github.com/GoogleCloudPlatform/appengine-gcs-client
https://cloud.google.com/appengine/docs/standard/java/googlecloudstorageclient/setting-up-cloud-storage

This maven plugin is not compatible with the gcloud SDK based maven plugin.

**Comment by loosebazooka** [comment] 2017-02-27 20:25
Can you elaborate?

**Comment by lesv** [comment] 2017-02-27 21:41
Yes - DevAppServer2 thing.  b/34039598

**Comment by akerekes** [comment] 2017-04-14 20:07
Duplicate of #106

**Closed by akerekes** 2017-04-14 20:07 UTC
