### ISSUE TITLE
Python.exe process is not killed after the server has been stopped

### ISSUE THREAD

**Issue by NicolaSpreafico** [GoogleCloudPlatform/app-maven-plugin#124] opened 2017-01-17 07:38 UTC
I have an App Engine project with the plugin configured as follows:
```
<!-- https://mvnrepository.com/artifact/com.google.cloud.tools/appengine-maven-plugin -->
<plugin>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>appengine-maven-plugin</artifactId>
    <version>1.0.0</version>
</plugin>
```

And here are the details about my GCloud installation
```
Google Cloud SDK [139.0.1]

Platform: [Windows, x86_64]
Python Version: [2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]]
Python Location: [C:\Users\Nicola\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\python.exe]
Site Packages: [Disabled]

Installation Root: [C:\Users\Nicola\AppData\Local\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  bundled-python: [2.7.10]
  app-engine-python: [1.9.49]
  core: [2017.01.12]
  core-win: [2016.11.07]
  app-engine-java: [1.9.48]
  gcloud: []
  windows-ssh-tools: [2016.05.13]
  beta: [2016.01.12]
  gsutil: [4.22]
  cloud-datastore-emulator: [1.2.1]
  gcd-emulator: [v1beta3-1.0.0]
  powershell: [1.0.0.1]
  gsutil-win: [4.20]

```

To launch the dev-server I use the following command:
```
mvn com.google.cloud.tools:appengine-maven-plugin:run --f "C:\Users\Nicola\Noovle\eclipse\workspace\session-test" > R:\out.log 2> R:\err.log
```

While the server is running you can clearly see the python.exe processes inside the TaskManager
![image](https://cloud.githubusercontent.com/assets/12278553/22011517/c10d24e0-dc8f-11e6-8fbd-1b9f3633b6c4.png)

Once I hit CTRL+C in the prompt in order to kill the server, the shell became idle but the python process is still alive. If I hit the http://localhost:8080/ page, the server replies correctly

Attached you can find the 2 logs generated from the previous command.
[out.txt](https://github.com/GoogleCloudPlatform/app-maven-plugin/files/710299/out.txt)
[err.txt](https://github.com/GoogleCloudPlatform/app-maven-plugin/files/710298/err.txt)
(One note here, I don't understand why the python command is logged inside the error stream instead of the standard output.)

I need to kill the python process from Task Manager to shutting down for good
Am I wrongly shutting down the server or there is a concrete problem here?

**Comment by loosebazooka** [comment] 2017-01-17 18:06
I think it's up to us to correctly handle ctrl+c. We'll look in to this.

**Comment by chanseokoh** [comment] 2017-01-17 18:22
I tested this myself. What is interesting is that the JVM process dies when pressing Ctrl+C. It's the Python process that remains alive. So, I think the signal is being handled. I wonder if this is the same issue as [this one](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1182).

**Comment by meltsufin** [comment] 2017-01-17 18:25
@NicolaSpreafico what happens if you run this command directly in Command Prompt and then use Ctrl+C to kill it?

```
C:\Users\Nicola\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\python.exe C:\Users\Nicola\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\dev_appserver.py C:\Users\Nicola\Noovle\eclipse\workspace\session-test\target\session-test-0.0.1-SNAPSHOT --jvm_flag=-Dappengine.user.timezone=UTC
```

Another thing you can try as a workaround is run the `appengine:stop` goal in a separate window.

In any case, we need to see why the kill signal is not getting propagated to the python process.

**Comment by chanseokoh** [comment] 2017-01-17 18:34
Sorry, forget about what I said earlier. I deleted my comment. (I can't reproduce this.)

**Comment by NicolaSpreafico** [comment] 2017-01-18 07:42
@loosebazooka 
Here a couple of additiona infos on how to reproduce the problem. I used a `tasklist` command to display running processes

At first I make sure that NO processes of Java/python exists
```
tasklist /v | find "python"
tasklist /v | find "java"
```
Both commands give 0 results

I now launch the dev-server with the mvn command
```
mvn com.google.cloud.tools:appengine-maven-plugin:run --f "C:\Users\Nicola\Noovle\eclipse\workspace\session-test"
```

2 processes of each application has been spawn
```
C:\Users\Nicola>tasklist /v | find "python"
python.exe                    9024 Console                    2     24.228 K Unknown         NS-NOOVLE\Nicola                                        0:00:00 N/D
python.exe                    1176 Console                    2     44.032 K Unknown         NS-NOOVLE\Nicola                                        0:00:00 N/D
```
```
C:\Users\Nicola>tasklist /v | find "java"
java.exe                      7956 Console                    2    174.320 K Unknown         NS-NOOVLE\Nicola                                        0:00:08 N/D
java.exe                      3188 Console                    2    103.608 K Unknown         NS-NOOVLE\Nicola                                        0:00:01 N/D
```

I can now hit `Ctrl+C` to kill the dev-server (the shell is now idle)
Let's not see the process that are still alive

```
C:\Users\Nicola>tasklist /v | find "python"
python.exe                    1176 Console                    2     44.032 K Unknown         NS-NOOVLE\Nicola                                        0:00:00 N/D
```

```
C:\Users\Nicola>tasklist /v | find "java"
java.exe                      3188 Console                    2    103.368 K Unknown         NS-NOOVLE\Nicola                                        0:00:01 N/D
```

At the end, I manually kill the remaining processes
```
C:\Users\Nicola>taskkill /IM python.exe /F
process "python.exe" with PID 1176 has been terminated
```
```
C:\Users\Nicola>taskkill /IM java.exe /F
process "java.exe" with PID 3188 has been terminated
```

**Comment by NicolaSpreafico** [comment] 2017-01-18 07:49
@meltsufin 
Launching directly the server with the `python.exe` command the kill works fine.

Here is the final command I used 
```
"C:\Users\Nicola\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\python.exe" "C:\Users\Nicola\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\dev_appserver.py" "C:\Users\Nicola\Noovle\eclipse\workspace\session-test\target\session-test-0.0.1-SNAPSHOT" --jvm_flag=-Dappengine.user.timezone=UTC
```

Here are the processes list after I launch the server
```
C:\Users\Nicola>tasklist /v | find "python"
python.exe                    1788 Console                    2     23.984 K Unknown         NS-NOOVLE\Nicola                                        0:00:00 N/D
python.exe                    3804 Console                    2     44.104 K Unknown         NS-NOOVLE\Nicola                                        0:00:00 N/D
```
```
C:\Users\Nicola>tasklist /v | find "java"
java.exe                      1528 Console                    2    102.552 K Unknown         NS-NOOVLE\Nicola                                        0:00:01 N/D
```
The difference here (compared to the Maven launch) is that only one `java.exe` is spawn

After I used Ctrl+C and the shell is idle no processes are shown (all 3 has been properly killed)

**Comment by meltsufin** [comment] 2017-01-18 16:57
Thanks for the additional details @NicolaSpreafico!

I'm able to reproduce this on Windows, but not on Linux.

@loosebazooka I'm not really sure why two python processes get spawned. The old gcloud plugin spawns only one, but it also has the issue on Windows where one of the Java processes hangs around after Ctrl+C.

**Comment by loosebazooka** [comment] 2017-01-18 23:06
For whatever reason, the ctrl+c when run through maven/gradle isn't propagated up to the devappserver (which when confronted with the signal, will shut down). We might have to capture this separate from the shutdown hook we currently are using (either that, or our shutdown hook isn't being hit).

@NicolaSpreafico you can shut down a ctrl+c'd devappserver fully with mvn appengine:stop (or gradle appengineStop) which doesn't fully fix the problem, but is a little better than you killing the processes manually.

**Comment by pradeeppatelgithub** [comment] 2020-01-21 00:51
Yes, I was able to shut down the server by opening a new window and using `mvn appengine:devserver_stop` to stop the server.

**Comment by suztomo** [comment] 2023-06-21 17:05
Closing this for obsolete. The workaround ("mvn appengine:devserver_stop") is available.

**Closed by suztomo** 2023-06-21 17:05 UTC
Labels: bug, p3
